---

- name: "REPOS | Install the EPEL repo"
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
  when: ansible_os_family == "RedHat"

- name: "USERS | Add DFIR accounts"
  user:
    name: "{{ item.username }}"
    groups: wheel
    append: yes
    createhome: yes
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
  with_items: "{{ users }}"
  tags:
    - users
  when: ansible_os_family == "RedHat"

- name: "USERS | Add DFIR accounts"
  user:
    name: "{{ item.username }}"
    groups: sudo
    append: yes
    createhome: yes
    shell: "{{ item.shell }}"
    state: "{{ item.state }}"
  with_items: "{{ users }}"
  tags:
    - users
  when: ansible_os_family == "Debian"

- name: "USERS | Add public key for DFIR users to authorized_keys file"
  authorized_key:
    user: "{{ item.username }}"
    manage_dir: yes
    key: "{{ lookup('file', 'files/users/{{ item.username }}.pub') }}"
  with_items: "{{ users }}"
  tags:
    - users

- name: "PACKAGES | Add some packages we will need"
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-devel
    - python-pip
    - openssl-devel
    - gcc
    - git
  when: ansible_os_family == "RedHat"

- name: "PACKAGES | Add some packages we will need"
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python-dev
    - python-pip
    - libssl-dev
    - gcc
    - git
  when: ansible_os_family == "Debian"

- name: "INSTALL APPS | Clone git repos for all of the tools we want"
  git:
    repo: "{{ item.repo }}"
    accept_hostkey: yes
    dest: "{{ item.dest }}"
  with_items:
    - { repo: "https://github.com/volatilityfoundation/volatility.git", dest: "/tmp/volatility" }

- name: "INSTALL APPS | Install volatility"
  command: python setup.py install
  args:
    chdir: /tmp/volatility
    creates: /bin/vol.py

- name: "INSTALL APPS | Install python libraries needed by volatility"
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - {name: pip, state: latest}
    - {name: wheel, state: present}
    - {name: pefile, state: present}
    - {name: future, state: present}
    - {name: pdbparse, state: present}
    - {name: pycrypto, state: present}
    - {name: distorm3, state: present}
    - {name: setuptools, state: latest}
  tags:
    - pylibs

- name: "INSTALL APPS | Install python libraries needed by volatility"
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    version: "{{ item.version }}"
  with_items:
    - { name: construct, state: present, version: 2.5.5-reupload }
    - { name: openpyxl, state: present, version: 2.1.2 }
  tags:
    - pylibs